services:
  web:
    image: node:22
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  backend:
    image: node:22
    ports:
      - "3001:3001"
    command: sh -c "yarn install && npx nodemon server.js"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/chatapp?schema=public
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"