services:
  web:
    image: node:22
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    image: node:22
    ports:
      - "3001:3001"
    command: sh -c "yarn install && npx nodemon server.ts"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"